name: SIAM Student Chapter Delft
timezone: Europe/Amsterdam
markdown: kramdown
paginate: 5
paginate_path: "news/page:num"

domain: sscdelft.github.io
author: SIAM Student Chapter Delft
email: siamsc-ewi@tudelft.nl
